// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0g0UoVfj9I2g8xv2Un5uXTBcPx-RccbQ',
    appId: '1:750098882666:web:4e8bc645a63e0c68916a13',
    messagingSenderId: '750098882666',
    projectId: 'travel-8c5ff',
    authDomain: 'travel-8c5ff.firebaseapp.com',
    databaseURL: 'https://travel-8c5ff-default-rtdb.firebaseio.com',
    storageBucket: 'travel-8c5ff.appspot.com',
    measurementId: 'G-BPREFTEXF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuHbcxY5PxMOq6nJ-VcAkLxp4LjPTCaYI',
    appId: '1:750098882666:android:1fbf7d8cb598fee9916a13',
    messagingSenderId: '750098882666',
    projectId: 'travel-8c5ff',
    databaseURL: 'https://travel-8c5ff-default-rtdb.firebaseio.com',
    storageBucket: 'travel-8c5ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwPA020S5x76MLNMULYQca8S5QeXRVM_8',
    appId: '1:750098882666:ios:90e637fdf491ec5c916a13',
    messagingSenderId: '750098882666',
    projectId: 'travel-8c5ff',
    databaseURL: 'https://travel-8c5ff-default-rtdb.firebaseio.com',
    storageBucket: 'travel-8c5ff.appspot.com',
    androidClientId: '750098882666-b6c4hrke466oqk7siqara5qkhau3t63n.apps.googleusercontent.com',
    iosClientId: '750098882666-o5vqm4j2m01i6niodnhrf7tlm0dmr1e2.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwPA020S5x76MLNMULYQca8S5QeXRVM_8',
    appId: '1:750098882666:ios:90e637fdf491ec5c916a13',
    messagingSenderId: '750098882666',
    projectId: 'travel-8c5ff',
    databaseURL: 'https://travel-8c5ff-default-rtdb.firebaseio.com',
    storageBucket: 'travel-8c5ff.appspot.com',
    androidClientId: '750098882666-b6c4hrke466oqk7siqara5qkhau3t63n.apps.googleusercontent.com',
    iosClientId: '750098882666-o5vqm4j2m01i6niodnhrf7tlm0dmr1e2.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0g0UoVfj9I2g8xv2Un5uXTBcPx-RccbQ',
    appId: '1:750098882666:web:4e8bc645a63e0c68916a13',
    messagingSenderId: '750098882666',
    projectId: 'travel-8c5ff',
    authDomain: 'travel-8c5ff.firebaseapp.com',
    databaseURL: 'https://travel-8c5ff-default-rtdb.firebaseio.com',
    storageBucket: 'travel-8c5ff.appspot.com',
    measurementId: 'G-BPREFTEXF7',
  );

}